"""CLI runner for re-heuristic policy validation against live game environment."""

from __future__ import annotations

import argparse
import logging
from statistics import mean
from typing import Any

from src.agent.re_heuristic import ReHeuristicAgent, ReHeuristicConfig
from src.env.game_env import GameEnv, GameEnvConfig
from src.env.random_policy_runner import _build_action_config, _build_reward_config, _build_reward_fn
from src.env.runner_tui import RunnerTuiSession
from src.training.rewards import RewardWeights
from src.training.train import run_agent_policy


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run re-heuristic policy episodes against live game env.")
    defaults = ReHeuristicConfig()
    parser.add_argument("--exe", default="868-HACK.exe", help="Target executable name.")
    parser.add_argument("--episodes", type=int, default=3, help="Number of episodes to run.")
    parser.add_argument("--max-steps", type=int, default=200, help="Max steps per episode.")
    parser.add_argument("--seed", type=int, default=None, help="Optional random seed for tie-breaks.")
    parser.add_argument(
        "--movement-keys",
        choices=("arrows", "wasd", "numpad"),
        default="arrows",
        help="Movement key mapping profile.",
    )
    parser.add_argument(
        "--prog-actions",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Include prog-slot actions (prog_slot_1..prog_slot_10 mapped to 1..0).",
    )
    parser.add_argument(
        "--reset-sequence",
        default="confirm",
        nargs="?",
        const="",
        help="Comma-separated reset actions; pass without a value to disable reset key sequence.",
    )
    parser.add_argument(
        "--focus-window",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Focus the game window during attach/reacquire (default: enabled).",
    )
    parser.add_argument(
        "--window-input",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Use window-targeted PostMessage input instead of global SendInput.",
    )
    parser.add_argument(
        "--tui",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Launch live state monitor TUI in a separate console window.",
    )
    parser.add_argument(
        "--tui-interval",
        type=float,
        default=0.5,
        help="Polling interval for the live TUI (seconds).",
    )
    parser.add_argument(
        "--step-through",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Pause before each action and wait for Enter in the TUI to advance.",
    )
    parser.add_argument(
        "--step-timeout",
        type=float,
        default=3.0,
        help="Per-step watchdog timeout in seconds.",
    )
    parser.add_argument(
        "--reset-timeout",
        type=float,
        default=15.0,
        help="Reset watchdog timeout in seconds.",
    )
    parser.add_argument(
        "--require-non-terminal-reset",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Require reset() to observe a non-terminal state before starting steps.",
    )
    parser.add_argument(
        "--low-health-threshold",
        type=int,
        default=defaults.low_health_threshold,
        help="Health threshold where re-heuristic can override baseline waiting behavior.",
    )
    parser.add_argument(
        "--enemy-prediction-horizon-steps",
        type=int,
        default=defaults.enemy_prediction_horizon_steps,
        help="Enemy lookahead depth used by baseline delegate safety checks.",
    )
    parser.add_argument(
        "--rule-pack-path",
        default=None,
        help="Optional JSON rule pack generated by the re-heuristic loop.",
    )
    parser.add_argument(
        "--mined-rules",
        action=argparse.BooleanOptionalAction,
        default=defaults.enable_mined_rules,
        help="Enable/disable mined rule-pack evaluation.",
    )
    default_weights = RewardWeights()
    parser.add_argument(
        "--reward-survival",
        type=float,
        default=default_weights.survival,
        help="Survival reward applied for non-terminal steps.",
    )
    parser.add_argument(
        "--reward-health-delta",
        type=float,
        default=default_weights.health_delta,
        help="Weight multiplied by (current_health - previous_health).",
    )
    parser.add_argument(
        "--reward-currency-delta",
        type=float,
        default=default_weights.currency_delta,
        help="Weight multiplied by (current_currency - previous_currency).",
    )
    parser.add_argument(
        "--reward-fail-penalty",
        type=float,
        default=default_weights.fail_penalty,
        help="Terminal fail penalty magnitude (applied as negative).",
    )
    parser.add_argument(
        "--print-reward-breakdown",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Print per-step reward component breakdown during execution.",
    )
    parser.add_argument(
        "--verbose-actions",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Enable re-heuristic action-choice logging.",
    )
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()
    if bool(args.step_through) and not bool(args.tui):
        parser.error("--step-through requires --tui.")
    effective_window_input = bool(args.window_input) or bool(args.step_through) or bool(args.tui)
    if effective_window_input and not bool(args.window_input):
        mode = "step-through" if bool(args.step_through) else "tui"
        print(
            f"{mode} enabled: using window-targeted input so actions still go to the game "
            "while the TUI window has focus."
        )
    if args.verbose_actions:
        logging.basicConfig(level=logging.INFO, format="%(message)s")

    reset_sequence = tuple(action.strip() for action in str(args.reset_sequence).split(",") if action.strip())
    reward_config = _build_reward_config(args)
    reward_fn = _build_reward_fn(
        reward_config=reward_config,
        print_breakdown=bool(args.print_reward_breakdown),
    )

    env: GameEnv | None = None
    tui = RunnerTuiSession(
        executable_name=str(args.exe),
        enabled=bool(args.tui),
        interval_seconds=float(args.tui_interval),
        step_through=bool(args.step_through),
    )
    try:
        env = GameEnv.from_live_process(
            executable_name=args.exe,
            config=GameEnvConfig(
                step_timeout_seconds=args.step_timeout,
                reset_timeout_seconds=args.reset_timeout,
                require_non_terminal_on_reset=bool(args.require_non_terminal_reset),
            ),
            reset_sequence=reset_sequence if reset_sequence else None,
            focus_window_on_attach=bool(args.focus_window),
            window_targeted_input=effective_window_input,
            action_config=_build_action_config(args.movement_keys, include_prog_actions=bool(args.prog_actions)),
            reward_fn=reward_fn,
        )
        tui.start()

        def _on_step(event: dict[str, Any]) -> None:
            tui.update(
                training_line=(
                    "episode={episode} step={step} reward={reward:.3f} total={total:.3f} "
                    "done={done} terminal={terminal}".format(
                        episode=event.get("episode_id"),
                        step=int(event.get("step_index", 0)) + 1,
                        reward=float(event.get("reward", 0.0)),
                        total=float(event.get("total_reward", 0.0)),
                        done=bool(event.get("done", False)),
                        terminal=event.get("terminal_reason") or "-",
                    )
                ),
                action_line="action={action} reason={reason}".format(
                    action=event.get("action"),
                    reason=event.get("action_reason") or "re_heuristic_select",
                ),
            )

        def _on_before_step(event: dict[str, Any]) -> None:
            tui.wait_for_step_advance(
                training_line=(
                    "episode={episode} step={step} total={total:.3f} waiting=enter".format(
                        episode=event.get("episode_id"),
                        step=int(event.get("step_index", 0)) + 1,
                        total=float(event.get("total_reward", 0.0)),
                    )
                ),
                action_line="action={action} reason={reason}".format(
                    action=event.get("action"),
                    reason=event.get("action_reason") or "re_heuristic_select",
                ),
            )

        assert env is not None
        results = run_agent_policy(
            env=env,
            agent=ReHeuristicAgent(
                config=ReHeuristicConfig(
                    low_health_threshold=int(args.low_health_threshold),
                    enemy_prediction_horizon_steps=max(int(args.enemy_prediction_horizon_steps), 0),
                    verbose_action_logging=bool(args.verbose_actions),
                    enable_mined_rules=bool(args.mined_rules),
                    rule_pack_path=str(args.rule_pack_path) if args.rule_pack_path else None,
                )
            ),
            episodes=args.episodes,
            max_steps_per_episode=args.max_steps,
            seed=args.seed,
            before_step_callback=_on_before_step if bool(args.step_through) else None,
            step_callback=_on_step if bool(args.tui) else None,
        )
    finally:
        if env is not None:
            env.close()
        tui.close()

    print("episode_id\tsteps\tdone\ttotal_reward\tterminal_reason")
    for result in results:
        print(
            f"{result.episode_id}\t{result.steps}\t{result.done}\t"
            f"{result.total_reward:.3f}\t{result.terminal_reason or ''}"
        )

    avg_steps = mean(result.steps for result in results)
    avg_reward = mean(result.total_reward for result in results)
    done_rate = sum(1 for result in results if result.done) / len(results)
    print(
        f"\nsummary episodes={len(results)} avg_steps={avg_steps:.2f} "
        f"avg_reward={avg_reward:.3f} done_rate={done_rate:.2%}"
    )


if __name__ == "__main__":
    main()

